// ==============================================================================
// 🚦 interview.routes.js - INTERVIEW API ROUTE DIRECTORY
// ==============================================================================
// This file connects incoming URLs to the right controller functions.
// Notice that EVERY endpoint uses `authMiddleware.authUser`!
// That means only logged-in users with a valid VIP cookie can access these!
// ==============================================================================

const express = require("express");
const authMiddleware = require("../middlewares/auth.middleware");
const interviewController = require("../controllers/interview.controller");
const upload = require("../middlewares/file.middleware");

const interviewRouter = express.Router();

// 1. POST /api/interview/ -> Upload resume + job description, analyze with AI, and save report
interviewRouter.post(
    "/",
    authMiddleware.authUser,
    upload.single("resume"),
    interviewController.generateInterViewReportController
);

// 2. GET /api/interview/ -> Get list of all previous reports generated by this logged-in user
interviewRouter.get(
    "/",
    authMiddleware.authUser,
    interviewController.getAllInterviewReportsController
);

// 3. GET /api/interview/report/:interviewId -> Get one specific report by its MongoDB ID
interviewRouter.get(
    "/report/:interviewId",
    authMiddleware.authUser,
    interviewController.getInterviewReportByIdController
);

// 4. POST /api/interview/resume/pdf/:interviewReportId -> Generate & download tailored resume PDF
interviewRouter.post(
    "/resume/pdf/:interviewReportId",
    authMiddleware.authUser,
    interviewController.generateResumePdfController
);

module.exports = interviewRouter;
