// ==============================================================================
// 🧠 interview.context.jsx - GLOBAL INTERVIEW MEMORY
// ==============================================================================
// In React, Context is like a shared whiteboard in a classroom.
// Instead of passing data manually from parent to child through lots of props,
// this whiteboard holds:
// - loading: True when the AI is cooking up our strategy or downloading PDF.
// - report: The active interview report currently being viewed.
// - reports: The list of all previous reports generated by this user.
// Any component inside <InterviewProvider> can look at or update this whiteboard!
// ==============================================================================

import { createContext, useState } from "react";

export const InterviewContext = createContext();

export const InterviewProvider = ({ children }) => {
    const [loading, setLoading] = useState(false);
    const [report, setReport] = useState(null);
    const [reports, setReports] = useState([]);

    return (
        <InterviewContext.Provider value={{ loading, setLoading, report, setReport, reports, setReports }}>
            {children}
        </InterviewContext.Provider>
    );
};